### ISSUE TITLE
ScriptHandler::installAssets requires DB connection on Symfony 2.8?

### ISSUE THREAD

**Issue by barat** [sensiolabs/SensioDistributionBundle#253]
Hello,
I have an ISSUE with this section of composer:
```
        "post-install-cmd": [
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets"
        ],
```
When I turn off Docker mysql container I'm getting an error:
```
[PDOException]                                                                
  SQLSTATE[HY000] [2003] Can't connect to MySQL server on 'X.X.X.X' (113)
```
I have DBAL and ORM 2.5 so I added server_version parameter to config.yml

```
doctrine:
    dbal:
        default_connection:   default
        connections:
            default:
                driver:   pdo_mysql
                server_version: %server_version%
                host:     %database_host%
                port:     %database_port%
                dbname:   %database_name%
                user:     %database_user%
                password: %database_password%
                charset:  UTF8

```

Does someone else have this issue?

EDIT:

Found the reason ... but I don't know why it's working like this...

So, I checked one thing and commented whole section of 

```
framework:
    session:
        handler_id: session.handler.pdo
        cookie_domain: %cookie_domain%
        cookie_lifetime: 86400
        cookie_secure: true
        cookie_httponly: true
        gc_maxlifetime: 86400
        gc_probability: 5
        gc_divisor: 100
services:
    pdo:
        class: PDO
        arguments:
          - "mysql:dbname=%database_name%;host=%database_host%;port=%database_port%"
          - %database_user%
          - %database_password%
        calls:
          - [setAttribute, [3, 2]]

    session.handler.pdo:
        class:     Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
        arguments: [@pdo, %pdo.db_options%]
```

I've got an error during installAssets:

```
post-install-cmd: Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installAssets


                                                 
  [LogicException]                               
  CSRF protection needs sessions to be enabled.  
                                                 


Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installAssets handling the post-install-cmd event terminated with an exception


                                                                               
  [RuntimeException]                                                           
  An error occurred when executing the "'assets:install --symlink '\''web'\''  
  '" command:                                                                  
                                                                               
    [LogicException]                                                           
    CSRF protection needs sessions to be enabled.                              
                                                                               
  .                                                                            
      
```
The CSRF error is because there was no session configured and I don't think it's related with My Issue. installAssets doesn't use CSRF.
Then I changed session driver to session.handler.memcache and everything went smooth ...

So the question now is why installAssets even using session?
